### PR TITLE
Feature/support query payload

### PR DESCRIPTION
**Pull request by SebiBurchi**

### CODE REVIEW

**Comment by clambin** [comment]
could you provide some more info in what this PR is aiming to achieve?  I've never seen a query request with a Values attribute. In what case is this present?

**Comment by SebiBurchi** [comment]
https://grafana.com/grafana/plugins/simpod-json-datasource/ look at this plugin, please. Sending query also supports having a payload. That payload is identified in the QueryRequest as values. For example if I do a query having a payload with a variable "test", in my datasource I can take that variable value using new added JSON property.

**Comment by SebiBurchi** [comment]
@clambin I've also added the 'omitempty' property for the backwards compatibility

**Comment by clambin** [comment]
At some point, simplejson was compatible with simpod-json-datasource, but it seems that plugin's API has drastically changed over time. 

Might justify a rewrite of simplejson (as the original simple-json-datasource is no longer being maintained), but at this point I have no bandwidth for that, I'm afraid.

**Comment by clambin** [comment]
so I gave this some more thought ...

- firstly, this PR does not seem to work with the latest version of simpod-json-datasource: the query request's Target doesn't have a "data" field.  It does have a Payload section.  Possibly that's what you're referring to and it got changed in a later release of that plugin (API does seem to change over releases)?

- I don't want to merge in changes for obsolete versions of a plugin.  From a support perspective, that's asking for trouble.

- On the other hand: simplejson simply doesn't work with the latest version of that plugin:  for one, it doesn't use the /search endpoint anymore, but a new /metric endpoint. So simplejson cannot support that plugin anymore. Leaving only SimpleJson as a supported plugin.

- Also, the SimpleJson plugin is no longer being maintained by Grafana.  So this package would need to support something else. simpod-json-datasource seems the most appropriate replacement.  But mixing simplejson and simpod would be tricky as the APIs are too different now.


For that reason, I wrote a new package that works with simpod-json-datasource: https://github.com/clambin/grafana-json-server.

I published a first release this evening.  Seems to work well in an example setting, while supporting all the new features in simpod: payloads, scoped variables, etc.   I haven't moved any real applications over to the new package, but I don't expect the API to change (much).

Maybe you can give this one a try?  Any feedback would be appreciated.


One question: in what context were you using simplejson?  I don't see anyone importing  it in https://pkg.go.dev/github.com/clambin/simplejson?

**Pull request closed without merging**
